### PR TITLE
Always move help channels to bottom

### PR DESCRIPTION
**Pull request by tjjfvi**
This will both allow for a static honeypot channel at the top as well as a convenient sort on the occupied help channels.

### CODE REVIEW

**Review by robertt — APPROVED** [review]
LGTM - has this been tested?

**Comment by tjjfvi** [comment]
@robertt Yes; it took a bit of fiddling to figure out what the `position` and `setPosition` values actually meant 😅

**Comment by tjjfvi** [comment]
@robertt Do you want me to rebase this branch onto master, or is the merge commit sufficient?

**Comment by robertt** [comment]
I'll merge this 😄

**Pull request merged**
