### PR TITLE
Allow ID and username instead of just mention for commands

### PR DESCRIPTION
**Pull request by LapinoLapidus**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Imlements #24. Allows using an ID or a username instead of mentioning a user for t!getrep, t!removerep and t!rep.
Example: 
- t!rep 191146743163781120
- t!getrep LapinoLapidus

Does this close any currently open issues?
------------------------------------------

#24 

Any relevant logs, error output, etc?
-------------------------------------

Nope.

Any other comments?
-------------------
Nope.

Where has this been tested?
---------------------------
Local instance

### CODE REVIEW

**Comment by Haxified** [comment]
Hello! Thanks for the contribution. Good changes, although I think it would be better for it to be put into a function, instead of repeating the code all around the codebase. Maybe a util function, resolveMember(string)?

**Comment by LapinoLapidus** [comment]
Do you want that function in something of a utility class?

Function is the same for getrep and rep but differs a bit for removerep since it requires to specify an amount. The removerep command could be changed to specify the amount *before* the username which would allow adding spaces in the username (which isn't possible now because the string is seperated with a space)?

**Comment by Haxified** [comment]
Yeah, separate into a util class, with 2 functions ig

**Comment by Haxified** [comment]
nice! Although i think it might be better to just have resolveMember instead of resolveMemberWithoutNameSpaces

**Pull request merged**
