### PR TITLE
feat: multi-language "thank you"

### PR DESCRIPTION
**Pull request by Josh-Cena**
As requested on Discord. Probably good enough for now, but eventually we may need a heuristic for every language in the "localization" category?

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Please squash-merge this, made too many commits 🤦‍♂️

**Review by ckiee — CHANGES_REQUESTED** [review]
CJK character is outside non-capturing group.

> Please squash-merge this, made too many commits :man_facepalming:

You can use git interactive rebase to rewrite history.

**Comment by Josh-Cena** [comment]
> CJK character is outside non-capturing group.

It's on purpose, because Chinese doesn't have word bounds.

> You can use git interactive rebase to rewrite history.

I didn't clone this repo and I don't feel like it's necessary 🤪

**Comment by ckiee** [comment]
> It's on purpose, because Chinese doesn't have word bounds.

That sounds like it's worth a comment. (:

**Review by ckiee — APPROVED** [review]

**Pull request merged**
