### PR TITLE
Add !kill command

### PR DESCRIPTION
**Pull request by tjjfvi**
Useful for development, and should help resolve the current double bottage

### CODE REVIEW

**Comment by tjjfvi** [comment]
(I can remove the ascii art if desired, it helps distinguish it from other logs but it was mostly because it amused me)

**Comment by alii** [comment]
Would probably want to restrict this to more than just people with `MANAGE_MESSAGES`. I think either a proper role for the bot or `MANAGE_SERVER` would be more apt.

**Comment by tjjfvi** [comment]
Huh, I thought I put it on `ADMINISTRATOR`. I think I moved back to `MANAGE_MESSAGES` since that's what all of the other restricted commands are.

**Comment by ronthecookie** [comment]
You may want to consider `CommonInhibitors.botAdminsOnly`.

**Review by alii — APPROVED** [review]

**Review by ronthecookie — APPROVED** [review]
LGTM.

**Review by robertt — APPROVED** [review]

**Pull request merged**
