### PR TITLE
Adds a way to grab the first line in a playground message

### PR DESCRIPTION
**Pull request by orta**
Let's call this about ~80% confident it will work without me properly testing it

### CODE REVIEW

**Comment by tjjfvi** [comment]
Maybe only trigger it if the first line is a comment? I feel like most of the time the top line of a playground link is pretty irrelevant.

**Comment by orta** [comment]
I don't disagree with that at all, but:

- I think there's value in being able to at least try to distinguish between different ones 
- I think this lets people see that feature exists and then next time they can use it better

**Comment by robertt** [comment]
I don't see anything wrong with the code, lets merge it and see if it works 💯 

(this is how you open source right?)

**Review by robertt — APPROVED** [review]

**Comment by robertt** [comment]
Sorry, I didn't see the conversation 🤦‍♂️

**Pull request merged**
