### PR TITLE
Move prefixes to `.env`

### PR DESCRIPTION
**Pull request by tjjfvi**
This will be useful for development; if multiple people have a bot running on the same server, they can set them to use different prefixes.

### CODE REVIEW

**Comment by orta** [comment]
Will this need to happen on the server before it can be merged?

**Comment by tjjfvi** [comment]
Yeah.

@robertt Can you add this to the env?:
```
PREFIXES=!,t!
```

**Comment by robertt** [comment]
Can we add some sort of default if the env is not present? Maybe just `!`?

**Review by ckiee — APPROVED** [review]

**Comment by ckiee** [comment]
Tested?

**Comment by tjjfvi** [comment]
Yup

**Pull request merged**
