### PR TITLE
swearing.js

### PR DESCRIPTION
**Pull request by Enitoni**
This pr removes redundant / irrelevant words from swearing.js

These are words that are:
- Irrelevant and or not offensive to any sane person
- Variations or edgecases of another word that is already censored (including these is futile, people will find a way to get around it regardless)

If you feel some words should not have been removed/left alone, feel free to add or remove them.

### CODE REVIEW

**Comment by Haxified** [comment]
@orta opinions on this?

**Comment by resynth1943** [comment]
Holy shit, that's so much smaller

**Comment by orta** [comment]
Not sold on all the removals of `fuck` and `shit`  et al personally

**Comment by Haxified** [comment]
@Enitoni can you fix what orta said? then i would be happy to merge

**Pull request closed without merging**
